{
    'name': 'Employee Service',
    'version': '1.0',
    'depends': ['base', 'mail', 'hr', 'web_hierarchy'],
    'author': 'Sridharan',
    'category': 'Human Resources',
    'description': 'Employee service',
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/employee_views.xml',
        'views/action_view.xml',
        'views/menuitems_view.xml',
        'views/employee_tag_views.xml',
        'views/info_view.xml',
        'views/attendance.xml',
        'views/leave_views.xml',
        'views/payslip.xml',
        'views/self_appraisal.xml',
        'views/employee_ticket.xml',
        'views/employee_feedback.xml',
        'views/department.xml',
        'reports/employee_report_template.xml',
        'reports/employee_report_action.xml',
    ],
    'images': ['static/description/icon.png'],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}
